#!/usr/bin/env bash

# get base dir regardless of execution location
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ "$SOURCE" != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SOURCE=$([[ "$SOURCE" = /* ]] && echo "$SOURCE" || echo "$PWD/${SOURCE#./}")
basedir=$(dirname "$SOURCE")

. "$basedir/scripts/init.sh"

paperstash() {
    STASHED=$(git stash)
}

paperunstash() {
    if [[ "$STASHED" != "No local changes to save" ]] ; then
        git stash pop
    fi
}

buildpaperclipjar() {
    cp -f scripts/base/basepaperclip.sh base/SportPaper/base/Paper/paperclip.sh
    cd base/SportPaper/base/Paper
    ./paperclip.sh
    basedir
}

case "$1" in
    "setup" | "s" | "upstream")
        cd "$basedir"
        scripts/upstream.sh
    ;;
    "build" | "b")
        log_info "Preparing to build Titanium"
        cd "$basedir"
        scripts/upstream.sh
        scripts/apply.sh "$basedir"
        mvn clean install
        buildpaperclipjar
    ;;
    "rb" | "rbp" | "rebuild")
    (
        set -e
        cd "$basedir"
        scripts/rebuildpatches.sh "$basedir"
    )
    ;;
    "p" | "patch" | "apply")
    (
        set -e
        cd "$basedir"
        scripts/apply.sh "$basedir"
        log_info "    Run './titanium jar' to create a runnable JAR."
    )
    ;;
    "j" | "jar")
    (
        set -e
        mvn clean install

        case "$2" in
          "paperclip" | "pc")
            buildpaperclipjar
          ;;
        esac
    )
    ;;
    "deploy")
    (
      set -e

      REPOSITORY='titanvale-snapshots::https://repo.titanvale.net/snapshots'

      case "$2" in
        "release")
          REPOSITORY='titanvale-releases::https://repo.titanvale.net/releases'
        ;;
      esac

      echo "Deploying to $REPOSITORY"

      basedir

      mvn clean install deploy:deploy -DaltDeploymentRepository=$REPOSITORY
    )
    ;;
    *)
        echo "Titanium build tool."
        echo ""
        echo " Commands:"
        echo "  * setup              | Setup the build environment"
        echo "  * build              | Setup the build environment, apply patches, and create a runnable JAR"
        echo "  * p, patch           | Apply patches"
        echo "  * rb, rebuild        | Rebuild patches"
        echo "  * j, jar             | Create a runnable JAR"
        echo "    * (pc, papeprclip) | Create runnable JAR with Paperclip"
        echo "  * deploy             | Deploy to maven repository"
        echo "    * (release)        | Define if deploy to releases repository, empty deploy to snapshots"
    ;;
esac

unset -f paperstash
unset -f paperunstash
