name: Titanium CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: adopt
          cache: maven
      - name: Setup Git
        run: |
          git config --global user.email "titanium@titanvale.net"
          git config --global user.name "Titanium CI"
      - name: Grant execute permissions
        run: |
          chmod -R +x ./base/
          chmod -R +x ./scripts/
      - name: Build Titanium
        run: bash titanium build
