name: Publish Titanium main to TitanVale repository

on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: "Setup Gradle cache"
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Setup Git
        run: |
          git config --global user.email "titanium@titanvale.net"
          git config --global user.name "Titanium CI/CD"
          git config --global init.defaultBranch main
      - name: Grant execute permissions
        run: |
          chmod -R +x ./base/
          chmod -R +x ./scripts/
          chmod +x gradlew
          chmod +x titanium
      - name: Prepare Titanium upstream
        run: ./titanium upstream
      - name: Apply Titanium patches
        run: ./titanium apply
      - name: Publish Titanium JAR
        run: ./gradlew publishAllPublicationsToReleasesRepository --no-daemon
        env:
          RELEASES_USERNAME: ${{ secrets.RELEASES_USERNAME }}
          RELEASES_PASSWORD: ${{ secrets.RELEASES_PASSWORD }}
